Numpy
==

import party
--

In [1]:
import numpy as np
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

>array type, shape, ndim

In [2]:
array1 = np.array([1,2,3])
print("array type:", type(array1))
print("array1 형태:",array1.shape)
print("array1: {}차원".format(array1.ndim))

array2 = np.array([[1,2,3],[2,3,4]])
print("array type:", type(array2))
print("array2 형태:",array2.shape)
print("array2: {}차원".format(array2.ndim))

array3 = np.array([[1,2,3]])
print("array type:", type(array3))
print("array3 형태:",array3.shape)
print("array3: {}차원".format(array3.ndim))


array type: <class 'numpy.ndarray'>
array1 형태: (3,)
array1: 1차원
array type: <class 'numpy.ndarray'>
array2 형태: (2, 3)
array2: 2차원
array type: <class 'numpy.ndarray'>
array3 형태: (1, 3)
array3: 2차원


>list to array, dtype

In [3]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


>astype

In [4]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.99])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


>range, zeros, ones

In [5]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

sequence_array2 = np.arange(1,10)
print(sequence_array2)
print(sequence_array2.dtype, sequence_array2.shape)

zero_array = np.zeros((2,3), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((2,3))
print(one_array)
print(one_array.dtype, one_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[1 2 3 4 5 6 7 8 9]
int32 (9,)
[[0 0 0]
 [0 0 0]]
int32 (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
float64 (2, 3)


>reshape

In [6]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3\n',array3)

#Value error
#array1.reshape(4,2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


>reshape(-1)

In [7]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print(array2)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
print(array3)

#Value error
#array4 = array1.reshape(-1,4)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


>reshape을 통해 차원 변형 예제

In [8]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d)
array3d.tolist()

array5 = array3d.reshape(-1,1)
print('array5 shape:',array5.shape)
print(array5.tolist())

array6 = array1.reshape(1,-1)
print('array6 shape:', array6.shape)
print(array6)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5 shape: (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (1, 8)
[[0 1 2 3 4 5 6 7]]


>Indexing

In [9]:
array1 = np.arange(start=1,stop=10)
print('array:',array1)

value = array1[2]
print('value:', value)
print(type(value))

value1 = array1[-2]
print('value1:',value1)
print(type(value1))

#데이터값 수정
array1[0] = 9
array1[8] = 0
print(array1)

array: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
value1: 8
<class 'numpy.int32'>
[9 2 3 4 5 6 7 8 0]


In [10]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print('array2d[0,0]:',array2d[0,0])
print('array2d[0,1]:',array2d[0,1])
print('array2d[2,0]:',array2d[2,0])
print('array2d[2,1]:',array2d[2,1])

array1d = np.arange(start=1,stop=9)
array3d = array1d.reshape(2,2,2)
print(array3d)
print(array3d.tolist())
print('array3d[0,0,0]:',array3d[0,0,0])
print('array3d[1,0,0]:',array3d[1,0,0])
print('array3d[0,1,0]:',array3d[0,1,0])
print('array3d[0,0,1]:',array3d[0,0,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0,0]: 1
array2d[0,1]: 2
array2d[2,0]: 7
array2d[2,1]: 8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
array3d[0,0,0]: 1
array3d[1,0,0]: 5
array3d[0,1,0]: 3
array3d[0,0,1]: 2


>Slicing

In [11]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

#2d Slicing
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[1:3,0:1] \n',array2d[1:3,0:1])
print('array2d[-1:,0] \n',array2d[-1:,0])
print('array2d[:,:-1]\n',array2d[:,:-1])

print('array2d[0] shape:', array2d[0].shape,'array2d[0]:', array2d[0])
print('array2d[2] shape:', array2d[2].shape,'array2d[2]:', array2d[2])
print('arrry2d')



[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:1] 
 [[4]
 [7]]
array2d[-1:,0] 
 [7]
array2d[:,:-1]
 [[1 2]
 [4 5]
 [7 8]]
array2d[0] shape: (3,) array2d[0]: [1 2 3]
array2d[2] shape: (3,) array2d[2]: [7 8 9]
arrry2d


>Fancy Indexing

In [12]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[0,1],2]\n->', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]\n->', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]\n->',array5.tolist())


array2d[0,1],2]
-> [3, 6]
array2d[[0,1],0:2]
-> [[1, 2], [4, 5]]
array2d[[0,1]]
-> [[1, 2, 3], [4, 5, 6]]


>Boolean Indexing

In [13]:
array1d = np.arange(start=1,stop=10)

array3 = array1d[array1d>5]
print('array1d[array1d>5]\n->', array3)

#why?
print('array1d.dtype:',array1d.dtype)
print('array1d > 5\n->',array1d > 5)

boolean_indexs = np.array([False, False, False, False, False, True, True, True, True])
print('array1d[boolean_indexs]\n->',array1d[boolean_indexs])

array2d = array1d.reshape(3,3)
print('array2d > 5:\n',array2d>5)
print('array2d[array2d>5]\n->',array2d[array2d>5])


array1d[array1d>5]
-> [6 7 8 9]
array1d.dtype: int32
array1d > 5
-> [False False False False False  True  True  True  True]
array1d[boolean_indexs]
-> [6 7 8 9]
array2d > 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
array2d[array2d>5]
-> [6 7 8 9]


>Sorting

In [14]:
original_array = np.array([3,1,9,4])
print('original_array:', original_array)
print('----------------------')
print('np.sort(original_array):', np.sort(original_array))
print('after np.sort(original_array)\n->original_array:',original_array)
print('----------------------')
sorted_array = original_array.sort()
print('original_array.sort():',original_array.sort())
print('after original_array.sort()\n->original_array:',original_array)
print('----------------------')

#Descending order sort(내림차순)
desc_sorted_array = np.sort(original_array)[::-1]
print('np.sort(original_array)[::-1]\n->',np.sort(original_array)[::-1])


original_array: [3 1 9 4]
----------------------
np.sort(original_array): [1 3 4 9]
after np.sort(original_array)
->original_array: [3 1 9 4]
----------------------
original_array.sort(): None
after original_array.sort()
->original_array: [1 3 4 9]
----------------------
np.sort(original_array)[::-1]
-> [9 4 3 1]


>2d array sort

In [15]:
array2d = np.array([[8, 12], [7, 1]])
print('array2d:\n',array2d)
print('----------------------')

axis0_sorted_array2d = np.sort(array2d, axis=0)
print('np.sort(array2d, axis=0):\n',axis0_sorted_array2d)
print('----------------------')

axis1_sorted_array2d = np.sort(array2d, axis=1)
print('np.sort(array2d, axis=1):\n',axis1_sorted_array2d)

array2d:
 [[ 8 12]
 [ 7  1]]
----------------------
np.sort(array2d, axis=0):
 [[ 7  1]
 [ 8 12]]
----------------------
np.sort(array2d, axis=1):
 [[ 8 12]
 [ 1  7]]


>Argsort

In [16]:
original_array = np.array([3,1,9,5])
sort_indices = np.argsort(original_array)
print(type(sort_indices))
print('np.argsort(original_array):\n',sort_indices)
print('----------------------')

#Desceding Order
descsort_indices = np.argsort(original_array)[::-1]
print('np.argsort(original_array)[::-1]:\n',descsort_indices)

<class 'numpy.ndarray'>
np.argsort(original_array):
 [1 0 3 2]
----------------------
np.argsort(original_array)[::-1]:
 [2 3 0 1]


In [17]:
name_array = np.array(['A','B','C','D','E'])
score_array = np.array([61,42,73,34,95])

ascsort_indices = np.argsort(score_array)
print('Index of score after ascending order sort:',ascsort_indices)
print('Name in order of score(ascending order):', name_array[ascsort_indices])

Index of score after ascending order sort: [3 1 0 2 4]
Name in order of score(ascending order): ['D' 'B' 'A' 'C' 'E']


>Linear Algebra(Dot Product, Transpose)

In [18]:
MatrixA = np.array([[1, 2, 3],
                    [4, 5, 6]])
MatrixB = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])
A_dotproduct_B = np.dot(MatrixA,MatrixB)
print('MatrixA*MatrixB:\n',A_dotproduct_B)

MatrixA*MatrixB:
 [[ 58  64]
 [139 154]]


In [19]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('----------------------')

array2d_T = np.transpose(array2d)
print('Transpose of array2d:\n',array2d_T)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------
Transpose of array2d:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
new_array = np.arange(1,10).reshape(3,3)
print(new_array)
new_array[:,2] = 8
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 8]
 [4 5 8]
 [7 8 8]]
