>Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', 'Refrigerator', 'Microwave', 'PC', 'Fan', 'Fan', 'Mixer', 'Mixer']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('Encoding Results:', labels)
print('Encoding Classes:', encoder.classes_)


Encoding Results: [5 4 1 3 0 0 2 2]
Encoding Classes: ['Fan' 'Microwave' 'Mixer' 'PC' 'Refrigerator' 'TV']


In [4]:
print('Original Value by Decoding:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

Original Value by Decoding: ['Refrigerator' 'TV' 'Mixer' 'Fan' 'Microwave' 'Microwave' 'PC' 'PC']


>One-Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#for one_hot encoding, we have to transform items into numerical value
items = ['TV', 'Refrigerator', 'Microwave', 'PC', 'Fan', 'Fan', 'Mixer', 'Mixer']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#for one_hot encoding, we have to transform labels into 2D array
labels = labels.reshape(-1,1)

onehot_encoder = OneHotEncoder()
onehot_encoder.fit(labels)
labels = onehot_encoder.transform(labels)

print('One-Hot Encoding Results:\n', labels, sep='')
print('Type of Labels:', type(labels.shape))
print('One-Hot Encoding Results toarray():\n', labels.toarray(), sep='')
print('Shape of Labels:', labels.shape)

One-Hot Encoding Results:
  (0, 5)	1.0
  (1, 4)	1.0
  (2, 1)	1.0
  (3, 3)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
Type of Labels: <class 'tuple'>
One-Hot Encoding Results toarray():
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
Shape of Labels: (8, 6)


In [11]:
#One-Hot Encoding by pandas
import pandas as pd

df = pd.DataFrame({'item':['TV', 'Refrigerator', 'Microwave', 'PC', 'Fan', 'Fan', 'Mixer', 'Mixer']})
pd.get_dummies(df)

item_Fan  item_Microwave  item_Mixer  item_PC  item_Refrigerator  item_TV
0         0               0           0        0                  0        1
1         0               0           0        0                  1        0
2         0               1           0        0                  0        0
3         0               0           0        1                  0        0
4         1               0           0        0                  0        0
5         1               0           0        0                  0        0
6         0               0           1        0                  0        0
7         0               0           1        0                  0        0