## Polynomial Regression & Overfitting/Underfitting

### Introduction to Polynomial Regression

Scikit-Learn does not explicitly provide Polynomial Regression Classes.  
Instead, we build polynomial regression model by applying non-linear function into linear regression model.  
With sklearn.preprocessing class PolynomialFeatures, we transform singular features into polynomial features.

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Linear Singular Feature X
X = np.arange(6).reshape(3,2)
print('One-Dimension Singular Coefficient Feature:\n')
print(X)

# Transform X into Two-Demension Polynomial Feature
# degree=2: [x1, x2] -> [1, x1, x2, x1**2, x1*x2, x2**2]
poly = PolynomialFeatures(degree=2)
poly.fit(X)                         # Can use poly_feature = poly.fit_transform(X)
poly_feature = poly.transform(X)
print('Transformed 2D Polynomial Coefficent Feature:')
print(poly_feature)

One-Dimension Singular Coefficient Feature:

[[0 1]
 [2 3]
 [4 5]]
Transformed 2D Polynomial Coefficent Feature:
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [4]:
# make func. y = 1 + 2X(1) + 3X(1)^2 + 4X(2)^3
def polynomial_func(X):
    y = 1+2*X[:,0] + 3*X[:,0]**2 + 4*X[:,1]**3
    return y

X = np.arange(6).reshape(3,2)
print('Linear Singular Feature X:')
print(X)

# Cubic Polynomial Decision Value
y = polynomial_func(X)
print('Cubic Polynomial Feature y:')
print(y)

 Singular Coefficients:
[[0 1]
 [2 3]
 [4 5]]
Cubic Polynomial Value:
[  5 125 557]


In [5]:
# Transform X into Cubic Polynomial Feature
poly= PolynomialFeatures(degree=3)
poly_feature = poly.fit_transform(X)
print('Cubic Polynomial Coefficients:')
print(poly_feature)

from sklearn.linear_model import LinearRegression
# Linear Regression Model with transformed features and Cubic Polynomial Decision Value
model = LinearRegression()
model.fit(poly_feature, y)

print('Polynomial Regression Coefficients')
print(np.round(model.coef_, 2))
print('Real Function Coefficients:')
print([1,])

Cubic Polynomial Coefficients:
[[  1.   0.   1.   0.   0.   1.   0.   0.   0.   1.]
 [  1.   2.   3.   4.   6.   9.   8.  12.  18.  27.]
 [  1.   4.   5.  16.  20.  25.  64.  80. 100. 125.]]
Polynomial Regression Coefficients
[ 0.    0.47  0.47  0.57  1.04  1.51 -0.3   0.27  1.31  2.81]
